apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/glusterfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  resturl: "http://192.168.1.189:8080"
  restuser: "admin"
  clusterid: "4da6e2bd6c6de92d20f93270776570c3"
  secretNamespace: "default"
  secretName: "heketi-secret"
  volumeType: "none"
  volumenameprefix: "k8s"
allowVolumeExpansion: true    
